### ISSUE TITLE
Nao foi possivel gerar o ZIP

### ISSUE THREAD

**Issue by renoleite** [michaelfp/pcf-cpfcnpj-control#3]
Ola Michael, parabens pelo trabalho com os controles PCF. Nao estou conseguindo gerar o ZIP para ambos seus PFC controls de CNPJ e Endereco, seria possivel subir o managed ZIP para o repositorio? Acredito ter alguma diferenca de versao de Framework ou algo assim aqui. Muito obrigado.

**Comment by michaelfp** [comment]
Olá. Qual o erro que esta acontecendo para você? Fiz aqui o build normalmente.  Pode colar o erro que está ocorrendo?

Igualmente já fiz o update com as atualizações do PCF e subi um release com o zip já. Para baixar acesse a área de release do projeto.

Qualquer dúvida entre em contato.

**Comment by renoleite** [comment]
Muito obrigado Michael, vou olhar lá. Na vdd o the CEP compilou, o de CNPJ que dá o erro anexo.
![Capture](https://user-images.githubusercontent.com/31674167/84579772-e6fd0100-ad9e-11ea-99b3-718e7e7fca14.PNG)

**Comment by michaelfp** [comment]
> Muito obrigado Michael, vou olhar lá. Na vdd o the CEP compilou, o de CNPJ que dá o erro anexo.
> ![Capture](https://user-images.githubusercontent.com/31674167/84579772-e6fd0100-ad9e-11ea-99b3-718e7e7fca14.PNG)

Você realizou a instalação do cliente do Power Apps Componente Framework?
